name: Test Generated Files Match

on:
  push

jobs:
  regen-boringssl:
    name: Check BoringSSL Files
    runs-on: ubuntu-latest
    container: golang:1.21-bookworm
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Regen & check BoringSSL files
        run: |
          # https://github.com/actions/runner/issues/2033
          chown -R $(id -u):$(id -g) $PWD
          make
          test -z "`git ls-files -d -m -o`"
